stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3.6.2-jdk-8
      shellScript: mvn clean install
    when:
      branch:
        include:
        - master
  when:
    branch: {}
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: idp/rancher-app-sample:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 192.168.0.56:5000
    env:
      PLUGIN_INSECURE: "true"
    when:
      branch:
        include:
        - master
  when:
    branch: {}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    when:
      branch:
        include:
        - master
  when:
    branch: {}
timeout: 60
branch:
  include:
  - master
notification: {}
